name: consumable_replacement_notification
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_picker: ^2.1.0
  google_sign_in: ^5.4.3
  http: ^0.13.5
  smooth_page_indicator: ^1.0.0+2
  toggle_switch: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - .env
